version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: sf_fire_db
      POSTGRES_USER: sf_fire_user
      POSTGRES_PASSWORD: sf_fire_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
